In [24]:
# Needs numpy<2
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.linear_model import LinearRegression, Ridge

In [3]:
import numpy as np

N = 10
D = 20
X = np.random.random((N, D))
y = np.random.random((N,))
X.shape, y.shape

((10, 20), (10,))

In [4]:
X_test = np.random.random((1, D))

In [25]:
model = Ridge(fit_intercept=False)
model.fit(X, y)
model.predict(X_test)

array([0.74223646])

In [26]:
model.coef_

array([-0.02099534,  0.09838221,  0.0434512 ,  0.0363666 ,  0.14917565,
        0.11205249, -0.1899224 ,  0.25641629,  0.22972918,  0.04446996,
       -0.16361987,  0.11724655,  0.1272474 , -0.03997212,  0.06707027,
       -0.0953991 ,  0.05262966,  0.09708378,  0.05028898,  0.01178977])

In [23]:
from sklearn.metrics.pairwise import linear_kernel
from sklearn.gaussian_process.kernels import DotProduct

linear = DotProduct(0.)
gp = GaussianProcessRegressor(linear, alpha=1.)
gp.fit(X, y)
gp.predict(X_test)

/home/jj/.local/lib/python3.10/site-packages/sklearn/gaussian_process/kernels.py:307: RuntimeWarning: divide by zero encountered in log
  return np.log(np.hstack(theta))
/home/jj/.local/lib/python3.10/site-packages/sklearn/gaussian_process/kernels.py:442: ConvergenceWarning: The optimal value found for dimension 0 of parameter sigma_0 is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(


array([0.74223646])

In [17]:
A = X.T @ X + np.eye(D)

In [22]:
opt = np.linalg.inv(A) @ X.T @ y
opt

array([-0.02099534,  0.09838221,  0.0434512 ,  0.0363666 ,  0.14917565,
        0.11205249, -0.1899224 ,  0.25641629,  0.22972918,  0.04446996,
       -0.16361987,  0.11724655,  0.1272474 , -0.03997212,  0.06707027,
       -0.0953991 ,  0.05262966,  0.09708378,  0.05028898,  0.01178977])

In [27]:
X_test @ opt

array([0.74223646])

In [28]:
y_pred, y_std = gp.predict(X_test, return_std=True)
y_std

array([1.23005279])

In [32]:
np.sqrt(X_test @ np.linalg.inv(A) @ X_test.T)

array([[1.23005279]])